name: Build CircuitPython UF2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install makeuf2
        run: |
          sudo apt update
          sudo apt install -y git build-essential cmake
          git clone https://github.com/microsoft/uf2.git
          cd uf2/uf2tool
          make
          sudo cp uf2conv /usr/local/bin/

      - name: Prepare project files
        run: |
          mkdir -p build/circuitpython
          cp -r code.py boot.py utils lib www build/circuitpython/

      - name: Build CircuitPython UF2
        run: |
          uf2conv build/circuitpython --base 0x10000000 --family 0xE48BFF56 -o build/uf2/project.uf2

      - name: Upload UF2 package
        uses: actions/upload-artifact@v4
        with:
          name: pico-w-project-uf2
          path: build/uf2/project.uf2
